[package]
name = "dll_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
winapi = "0.2"
kernel32-sys = "0.2"
minhook = { path = "./minhook" }